// Auto-generated from 英语常用句子100句.md
#pragma once

#define PHRASE_COUNT 100
#define PHRASE_PER_GROUP 25
#define PHRASE_GROUPS 4

static const char *s_ph_en[PHRASE_COUNT] = {
    "Hello!",
    "Good morning!",
    "Good afternoon!",
    "Good evening!",
    "Good night!",
    "How are you?",
    "I'm fine, thank you.",
    "Nice to meet you!",
    "My name is...",
    "What's your name?",
    "How old are you?",
    "I'm seven years old.",
    "Thank you!",
    "You're welcome!",
    "Sorry.",
    "It's OK.",
    "Please.",
    "Can I help you?",
    "Yes, please.",
    "No, thank you.",
    "Excuse me.",
    "I'm sorry.",
    "That's all right.",
    "See you later!",
    "Bye-bye!",
    "Let's go!",
    "Wait a moment.",
    "Hurry up!",
    "Let's play!",
    "I like it.",
    "I don't like it.",
    "It's delicious!",
    "I'm hungry.",
    "I'm thirsty.",
    "I'm tired.",
    "I'm happy.",
    "I'm sad.",
    "I'm scared.",
    "I'm angry.",
    "Don't worry.",
    "It's time to...",
    "Let's have breakfast!",
    "Let's have lunch!",
    "Let's have dinner!",
    "Can I have some...",
    "Can you give me...?",
    "I want to...",
    "I need to...",
    "Let's go to...",
    "Where is...? ...",
    "How do I get to...?",
    "Turn left.",
    "Turn right.",
    "Go straight.",
    "It's next to...",
    "It's in front of...",
    "It's behind...",
    "What's this?",
    "What's that?",
    "This is...",
    "That is...",
    "It's a...",
    "I have...",
    "Do you have...?",
    "Let me see.",
    "Look!",
    "Listen!",
    "Look at...",
    "I can...",
    "Can you...?",
    "I can't...",
    "Let me try.",
    "Try again.",
    "Good job!",
    "Well done!",
    "Great!",
    "Wonderful!",
    "Cool!",
    "Awesome!",
    "Come on!",
    "Be careful!",
    "Don't...",
    "Stop!",
    "Be quiet!",
    "Sit down, please.",
    "Stand up, please.",
    "Open your book.",
    "Close your book.",
    "Listen to me.",
    "Follow me.",
    "Repeat after me.",
    "Do you understand?",
    "I understand.",
    "I don't understand.",
    "Can you say it again?",
    "One more time.",
    "I agree.",
    "I disagree.",
    "Maybe.",
    "Of course!",
};

static const char *s_ph_cn[PHRASE_COUNT] = {
    "你好！",
    "早上好！",
    "下午好！",
    "晚上好！",
    "晚安！",
    "你好吗？",
    "我很好，谢谢。",
    "很高兴认识你！",
    "我叫...",
    "你叫什么名字？",
    "你几岁了？",
    "我七岁了。",
    "谢谢！",
    "不客气！",
    "对不起。",
    "没关系。",
    "请。",
    "需要帮忙吗？",
    "是的，请。",
    "不了，谢谢。",
    "借过/劳驾。",
    "我很抱歉。",
    "没关系的。",
    "待会见！",
    "再见！",
    "走吧！",
    "等一下。",
    "快点！",
    "一起玩吧！",
    "我喜欢它。",
    "我不喜欢它。",
    "很好吃！",
    "我饿了。",
    "我渴了。",
    "我累了。",
    "我很开心。",
    "我很难过。",
    "我害怕。",
    "我生气了。",
    "别担心。",
    "是时候...了。",
    "吃早餐吧！",
    "吃午餐吧！",
    "吃晚餐吧！",
    "我可以...吗？",
    "你能给我...吗？",
    "我想要...",
    "我需要...",
    "一起去...吧！",
    "在哪里？",
    "我怎么去...？",
    "左转。",
    "右转。",
    "直走。",
    "在...旁边。",
    "在...前面。",
    "在...后面。",
    "这是什么？",
    "那是什么？",
    "这是...",
    "那是...",
    "这是一个...",
    "我有...",
    "你有...吗？",
    "让我看看。",
    "看！",
    "听！",
    "看...。",
    "我会...",
    "你会...吗？",
    "我不会...",
    "让我试试。",
    "再试一次。",
    "干得好！",
    "做得好！",
    "太棒了！",
    "太好了！",
    "好酷！",
    "太棒了！",
    "加油！/快点！",
    "小心！",
    "不要...",
    "停下！",
    "安静！",
    "请坐。",
    "请起立。",
    "打开书。",
    "合上书。",
    "听我说。",
    "跟我学。",
    "跟我读。",
    "你懂了吗？",
    "我懂了。",
    "我不懂。",
    "你能再说一次吗？",
    "再一次。",
    "我同意。",
    "我不同意。",
    "也许。",
    "当然！",
};

static const int s_ph_range[PHRASE_GROUPS][2] = {
    {0, 25},
    {25, 25},
    {50, 25},
    {75, 25},
};
